bug: fix querier return empty array
orange-cloudavenue/cloudavenue-sdk-go pull request #101
Opened 2024-03-29 10:00 UTC by dmicheneau

```
PASS
coverage: 89.4% of statements
ok      github.com/orange-cloudavenue/cloudavenue-sdk-go/pkg/uuid       0.179s  coverage: 89.4% of statements
```

The code was tested from cav binary successfully.

2024-03-29 10:11 UTC, dmicheneau commented
The querier do not return an error, so now the sdk return a nil object if doesn't exist.

2024-03-29 11:47 UTC, azrod requested changes

2024-03-29 11:47 UTC, azrod commented on v1/querier.go
> +	if r.Results.OrgVdcRecord == nil {
VappRecord

2024-04-11 07:52 UTC, azrod approved these changes

2024-04-11 07:53 UTC, merged