chore: Add Service Port and retry func
orange-cloudavenue/cloudavenue-sdk-go pull request #166
Opened 2024-12-13 14:37 UTC by dmicheneau

2024-12-13 15:12 UTC, azrod requested changes

2024-12-13 15:12 UTC, azrod commented on v1/edgegw_alb_virtual_service.go
> +	// time.Sleep(10 * time.Second)
```suggestion
```

2024-12-13 15:12 UTC, azrod commented on v1/edgegw_alb_virtual_service.go
Missing catch error

2024-12-13 15:12 UTC, azrod commented on .changelog/166.txt
> +`edgateway/virtualsevice` - Now the struct `EdgeGatewayALBVirtualServiceModel` implement simplify struct EdgeGatewayALBVirtualServiceModelServicePort for a service port.
```suggestion
`edgateway/virtualsevice` - Now the struct `EdgeGatewayALBVirtualServiceModel` implement simplified struct `EdgeGatewayALBVirtualServiceModelServicePort` for a service port.
```

2025-02-05 13:36 UTC, dmicheneau commented on v1/edgeloadbalancer/service_engine_group_types.go
> +		// NumDeployedVirtualServices is a deployed virtual services
```suggestion
		// NumDeployedVirtualServices is a number of deployed virtual services
```

2025-02-05 13:36 UTC, dmicheneau commented on v1/edgeloadbalancer/pool.go
> +var updatePool = func(poolClient fakePoolClient, pool *govcdtypes.NsxtAlbPool) (*govcd.NsxtAlbPool, error) {
// used for mock test only

2025-02-05 13:36 UTC, dmicheneau commented on v1/edgeloadbalancer/pool.go
> +var deletePool = func(poolClient fakePoolClient) error {
// used only for mock test

2025-02-05 13:37 UTC, azrod commented on v1/edgeloadbalancer/pool.go
> +var updatePool = func(poolClient fakePoolClient, pool *govcdtypes.NsxtAlbPool) (*govcd.NsxtAlbPool, error) {
No. Not only for test

2025-02-05 13:37 UTC, azrod commented on v1/edgeloadbalancer/pool.go
> +var deletePool = func(poolClient fakePoolClient) error {
No. Not only for test

2025-02-06 10:17 UTC, merged